### ISSUE TITLE
New currency - Czech crown

### ISSUE THREAD

**Issue by Kuldas** [doefom/currency-fieldtype#11]
Hi
can you add my national currency? I'd like to make a PR, but I couldn't find anywhere what to edit. 
Just add to `src/Utils/Currencies.php`? 

My national currency is Czech crowns and here the necessary things:

> **Mark** = CZK (In Czechia we use Kč)
> **Name** = Czech crown
> **Numeric code** = 203

Source - https://www.iso.org/obp/ui/#iso:code:3166:CZ

**Comment by doefom** [comment]
Hi @Kuldas, thank's for reaching out!

Your approach is totally right. Added the currency in version v1.2.3 :)
