### ISSUE TITLE
Missing currency when using default currency in Statamic 5

### ISSUE THREAD

**Issue by daun** [doefom/currency-fieldtype#14]
Hi! When using USD as currency, Statamic 5 will remove the `iso` key from the field config since [default values are now removed from blueprints](https://github.com/statamic/cms/pull/10272). However, the addon still expects the value to be non-null. The result is that using USD as currency is currently impossible and fails with an error or empty output.

The solution is probably adding the default value to the [augmented instance's iso getter](https://github.com/doefom/currency-fieldtype/blob/main/src/Augmentables/AugmentedCurrency.php#L111) as well to deal with the unexpected `null` value.

**Comment by doefom** [comment]
Hi @daun, thanks for reaching out! This might take a little while for me to look into this. You are most likely correct about the problem and your approach to fix it. Feel free to open a PR if you got some spare time, I'm happy to review it!

**Comment by daun** [comment]
@doefom No worries, sent you a pull request with a suggested fix :)

**Comment by doefom** [comment]
@daun awesome, thanks! That was super fast :D I think we'll get this merged today

**Comment by doefom** [comment]
Fixed with #15. @daun thanks for the PR!

**Comment by daun** [comment]
Thanks!
