### ISSUE TITLE
Field breaks inside of replicator

### ISSUE THREAD

**Issue by caseydwyer** [doefom/currency-fieldtype#2]
When the Currency fieldtype is used within a Replicator, it breaks due to static/repeated `ID` values. Here's what the console spits out, along with the multiple elements:

![image](https://github.com/doefom/currency-fieldtype/assets/13950848/26ccc651-5219-4e7e-b6b8-230132450742)

Taking a look under the hood, it seems like the `Currency.vue` component is maybe missing an import of Statamic's `Fieldtype.vue`? Not 100% sure about that, but if accurate then this a pretty easy fix. 👍

**Comment by doefom** [comment]
Again, thank you very much! Will merge this as soon as possible.
